development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: quickstart_development
  pool: 5
  username: postgres
  password: postgres

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: quickstart_development
  pool: 5
  username: postgres
  password: postgres
